const KEY="TQ6";let S=JSON.parse(localStorage.getItem(KEY)||"null")||{xp:0,done:0,correct:0,wrong:0,cat:{},streak:0};let run=[],i=0,locked=false,mode="mission";
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function shell(body){document.getElementById("app").innerHTML=`<div class="app"><div class="top"><div class="logo">TEACHER <b>QUEST</b></div><div class="xp">⚡ ${S.xp} XP</div></div>${body}</div><div class="nav"><button onclick="home()">🏠<small>หน้าหลัก</small></button><button onclick="modes()">🎮<small>เล่น</small></button><button onclick="academy()">🧠<small>เรียน</small></button><button onclick="stats()">📊<small>สถิติ</small></button></div>`}
function home(){shell(`<section class="hero"><div class="orb">🎓</div><span class="pill">V6 · ULTIMATE ACADEMY</span><h1>ภารกิจครู<br>มืออาชีพ</h1><p class="sub">คลังแนวข้อสอบ + โจทย์ต่อยอด + การสอนแบบเข้าใจเหตุผล<br>เล่นทีละข้อและพัฒนาจุดอ่อนของตัวเอง</p><button class="primary" onclick="start('mission')">เริ่มภารกิจ ✨</button></section><div class="grid"><button class="tile" onclick="start('mission')">⚔️<b>Mission Mix</b><span>คละหมวดแบบสนามจริง</span></button><button class="tile" onclick="start('boss')">👑<b>Boss Scenario</b><span>สถานการณ์วิเคราะห์</span></button><button class="tile" onclick="start('speed')">⚡<b>Quick Run</b><span>รอบสั้น 5 ข้อ</span></button><button class="tile" onclick="academy()">🧠<b>Academy</b><span>เรียนหลักคิดก่อนลงสนาม</span></button></div><div class="update">V6: ปรับคลังคำถาม • ปรับคำอธิบาย • เพิ่มหลายโหมด • เพิ่มสถิติรายหมวด • ปรับ UI มือถือ</div>`)}
function modes(){shell(`<div class="card"><h2>🎮 เลือกภารกิจ</h2>${[['mission','⚔️','Mission Mix','คละหมวดเหมือนสนามจริง'],['boss','👑','Boss Scenario','เน้นสถานการณ์และการวิเคราะห์'],['speed','⚡','Quick Run','5 ข้อ กระชับ รวดเร็ว'],['study','📚','Study Run','ตอบแล้วเรียนทันที เน้นทบทวน']].map(x=>`<button class="mode" onclick="start('${x[0]}')"><div class="icon">${x[1]}</div><div><b>${x[2]}</b><div class="small">${x[3]}</div></div></button>`).join("")}</div>`)}
function start(m){mode=m;let n=m==='speed'?5:m==='boss'?Math.min(8,BANK.length):Math.min(10,BANK.length);let pool=m==='boss'?BANK.filter(x=>x.kind.includes('ต่อยอด')):BANK;run=shuffle(pool.length?pool:BANK).slice(0,n);i=0;question()}
function question(){locked=false;let x=run[i],o=shuffle(x.c.map((t,n)=>({t,n})));shell(`<div class="card"><span class="pill">${x.cat}</span> <span class="pill">${x.kind}</span><div class="progress"><i style="width:${i/run.length*100}%"></i></div><div class="small">ภารกิจ ${i+1} / ${run.length}</div><div class="q">${x.q}</div><div id="choices">${o.map(z=>`<button class="choice" onclick="answer(${z.n},this)">${z.t}</button>`).join("")}</div><div id="result"></div></div>`)}
function answer(n,b){if(locked)return;locked=true;let x=run[i],ok=n===x.a;b.classList.add(ok?"good":"bad");document.querySelectorAll(".choice").forEach(e=>{e.disabled=true;if(e.textContent===x.c[x.a])e.classList.add("good")});S.done++;ok?(S.correct++,S.xp+=20,S.streak++):(S.wrong++,S.xp+=5,S.streak=0);S.cat[x.cat]??={d:0,c:0};S.cat[x.cat].d++;if(ok)S.cat[x.cat].c++;save();document.getElementById("result").innerHTML=`<div class="explain"><h3>${ok?"🎉 ถูกต้อง!":"🧩 ยังไม่ถูก — ข้อนี้สำคัญ"}</h3><div class="box"><b>คำตอบที่ถูก:</b> ${x.c[x.a]}</div><p><b>🔎 ทำไม?</b><br>${x.why}</p><p><b>🧠 ต้องเข้าใจอะไร?</b><br>${x.teach}</p><p><b>🎯 เทคนิคจับโจทย์</b><br>${x.trap}</p><div class="source">${x.src||"โจทย์ฝึกที่สร้างต่อยอดจากแนวคิดในคลัง"}</div><button class="primary next" onclick="${i+1<run.length?"nextQ()":"finish()"}">${i+1<run.length?"ไปข้อถัดไป →":"สรุปภารกิจ →"}</button></div>`}
function nextQ(){i++;question();scrollTo(0,0)}
function finish(){let acc=S.done?Math.round(S.correct/S.done*100):0;shell(`<section class="hero"><div class="orb">🏆</div><span class="pill">MISSION COMPLETE</span><h1>ภารกิจจบแล้ว!</h1><p class="sub">ตอบถูกสะสม ${S.correct} ข้อจาก ${S.done} ข้อ<br>ความแม่นยำสะสม ${acc}% · XP ${S.xp}</p><button class="primary" onclick="start('${mode}')">เล่นรอบใหม่</button></section>`)}
function academy(){shell(`<div class="card"><span class="pill">ACADEMY</span><h2>🧠 ห้องเรียนหลักคิด</h2><p><b>1. Alignment</b><br>เป้าหมาย → หลักฐาน → วิธีประเมิน ต้องตอบคำถามเดียวกัน</p><p><b>2. Validity</b><br>จะวัดอะไร ต้องเลือกเครื่องมือที่ทำให้เห็นสิ่งนั้นจริง</p><p><b>3. Learner-centered</b><br>เริ่มจากผู้เรียน ความแตกต่าง ความต้องการ และบริบท</p><p><b>4. Digital Literacy</b><br>ยอดแชร์ ≠ ความน่าเชื่อถือ ตรวจแหล่งที่มาและหลักฐาน</p><p><b>5. PDCA</b><br>Plan → Do → Check → Act คือวงจรของการพัฒนา</p><p><b>6. Counseling</b><br>ฟังและสำรวจก่อนรีบสรุปหรือให้คำแนะนำ</p><button class="primary next" onclick="start('study')">เอาหลักคิดไปลงสนาม 🎯</button></div>`)}
function stats(){let rows=Object.entries(S.cat).map(([c,v])=>{let p=Math.round(v.c/v.d*100);return `<div class="catrow"><div class="stat"><span>${c}</span><b>${v.c}/${v.d} (${p}%)</b></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join("");shell(`<div class="card"><h2>📊 ห้องวิเคราะห์</h2><div class="stat"><span>ทำสะสม</span><b>${S.done}</b></div><div class="stat"><span>ถูก</span><b>${S.correct}</b></div><div class="stat"><span>ผิด</span><b>${S.wrong}</b></div><div class="stat"><span>Streak</span><b>🔥 ${S.streak}</b></div><h3>ความแข็งแรงรายหมวด</h3>${rows||'<p class="small">เริ่มเล่นเพื่อสร้างข้อมูล</p>'}<button class="secondary" onclick="resetAll()">รีเซ็ตความก้าวหน้า</button></div>`)}
function resetAll(){if(confirm("รีเซ็ต XP และสถิติทั้งหมด?")){localStorage.removeItem(KEY);location.reload()}}
home();