const S='TQV4';let s=JSON.parse(localStorage.getItem(S)||'null')||{xp:0,seen:[],wrong:[],cat:{},streak:0};let q=[],i=0;
function save(){localStorage.setItem(S,JSON.stringify(s))}
function shuffle(a){return a.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function home(){document.getElementById('panel').innerHTML=''}
function start(){q=shuffle(TQ_QUESTIONS).slice(0,8);i=0;play()}
function showMap(){document.getElementById('panel').innerHTML='<div class="card"><h2>🗺️ แผนที่ด่าน</h2>'+[...new Set(TQ_QUESTIONS.map(x=>x.category))].map(c=>`<p><span class="pill">${c}</span></p>`).join('')+'</div>'}
function showLessons(){document.getElementById('panel').innerHTML='<div class="card"><h2>🧠 Academy</h2><p class="muted">เรียนหลักคิดก่อนลุย: Alignment, Validity, Digital Citizenship, QA วงจรพัฒนา และ Scaffolding</p><p>ระบบจริงควรขยายบทเรียนภาษาไทยเป็นคลังความรู้เต็มรูปแบบ พร้อมทบทวนแบบ spaced repetition</p></div>'}
function showStats(){let html='<div class="card"><h2>📊 วิเคราะห์ตัวเอง</h2>';for(const [c,v] of Object.entries(s.cat||{})){html+=`<p><b>${c}</b> — ${v.correct||0}/${v.seen||0}</p>`}html+=`<p>XP ${s.xp} · ทำแล้ว ${s.seen.length} ข้อ · ผิด ${s.wrong.length} ข้อ</p></div>`;document.getElementById('panel').innerHTML=html}
function play(){let x=q[i];let opts=shuffle(x.c.map((t,n)=>({t,n})));document.getElementById('panel').innerHTML=`<div class="card"><span class="pill">${x.category}</span> <span class="pill">${x.type==='source'?'จากคลังต้นฉบับ':'สร้างใหม่จากแนวคิดคลัง'}</span><h2>${i+1}/${q.length}</h2><h3>${x.q}</h3><div id="opts">${opts.map(o=>`<button class="choice" onclick="ans(${o.n},this)">${o.t}</button>`).join('')}</div><div id="exp"></div></div>`}
function ans(n,btn){if(btn.disabled)return;let x=q[i],ok=n===x.a;document.querySelectorAll('.choice').forEach(b=>b.disabled=true);btn.classList.add(ok?'ok':'bad');if(!ok)document.querySelectorAll('.choice').forEach(b=>{if(b.textContent===x.c[x.a])b.classList.add('ok')});s.xp+=ok?15:4;if(!ok&&!s.wrong.includes(x.id))s.wrong.push(x.id);if(!s.seen.includes(x.id))s.seen.push(x.id);s.cat[x.category]=s.cat[x.category]||{seen:0,correct:0};s.cat[x.category].seen++;if(ok)s.cat[x.category].correct++;save();document.getElementById('exp').innerHTML=`<div class="card"><h3>${ok?'✅ ถูกต้อง':'❌ ยังไม่ถูก'}</h3><p><b>ทำไม:</b> ${x.why}</p><p><b>สอนเพิ่ม:</b> ${x.teach}</p><p><b>เทคนิค:</b> ${x.tip}</p><p class="muted">${x.source}</p><button onclick="next()">ไปต่อ →</button></div>`}
function next(){i++;if(i<q.length)play();else{document.getElementById('panel').innerHTML='<div class="card"><h2>🎉 ภารกิจจบ</h2><p>ข้อที่พลาดถูกเก็บไว้สำหรับระบบ Review และหมวดที่อ่อนจะถูกใช้วางแผนการฝึกครั้งต่อไป</p><button onclick="start()">เล่นอีกครั้ง</button><button onclick="showStats()">ดูวิเคราะห์</button></div>'}}
