const KEY="TQ5";let S=JSON.parse(localStorage.getItem(KEY)||"null")||{xp:0,done:0,correct:0,wrong:0,cat:{}};let run=[],i=0,locked=false;
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function shell(body){document.getElementById("app").innerHTML=`<div class="app"><div class="top"><div class="logo">TEACHER <b>QUEST</b></div><span>⚡ ${S.xp} XP</span></div>${body}</div><div class="nav"><button onclick="home()">🏠<small>หน้าหลัก</small></button><button onclick="map()">🗺️<small>ด่าน</small></button><button onclick="academy()">🧠<small>เรียน</small></button><button onclick="stats()">📊<small>สถิติ</small></button></div>`}
function home(){shell(`<section class="hero"><div class="mascot">🎓</div><span class="pill">V5 · ADVENTURE ACADEMY</span><h1>ภารกิจครู<br>มืออาชีพ</h1><p>เล่นทีละข้อ เรียนจากเหตุผลจริง และสะสมความชำนาญไปพร้อมกัน</p><button class="primary" onclick="start()">เริ่มภารกิจ ✨</button></section><div class="grid"><button class="tile" onclick="start()">⚔️<b>ภารกิจวันนี้</b><span>ข้อเดียวต่อหนึ่งหน้า</span></button><button class="tile" onclick="map()">🗺️<b>แผนที่ด่าน</b><span>เส้นทางการฝึก</span></button><button class="tile" onclick="academy()">🧠<b>Academy</b><span>เรียนหลักคิดสั้น ๆ</span></button><button class="tile" onclick="stats()">📊<b>วิเคราะห์</b><span>ดูจุดแข็งและจุดที่ต้องฝึก</span></button></div>`)}
function start(){run=shuffle(BANK).slice(0,Math.min(10,BANK.length));i=0;question()}
function question(){locked=false;let x=run[i],o=shuffle(x.c.map((t,n)=>({t,n})));shell(`<div class="card"><span class="pill">${x.cat}</span> <span class="pill">${x.kind}</span><div class="progress"><i style="width:${i/run.length*100}%"></i></div><div class="mini">ข้อ ${i+1} / ${run.length}</div><div class="q">${x.q}</div><div id="choices">${o.map(z=>`<button class="choice" onclick="answer(${z.n},this)">${z.t}</button>`).join("")}</div><div id="result"></div></div>`)}
function answer(n,b){if(locked)return;locked=true;let x=run[i],ok=n===x.a;b.classList.add(ok?"good":"bad");document.querySelectorAll(".choice").forEach(e=>{e.disabled=true;if(e.textContent===x.c[x.a])e.classList.add("good")});S.done++;ok?(S.correct++,S.xp+=15):(S.wrong++,S.xp+=3);S.cat[x.cat]??={d:0,c:0};S.cat[x.cat].d++;if(ok)S.cat[x.cat].c++;save();document.getElementById("result").innerHTML=`<div class="explain"><h3>${ok?"🎉 ถูกต้อง":"🧩 ยังไม่ถูก"}</h3><div class="key"><b>คำตอบที่ถูก:</b> ${x.c[x.a]}</div><p><b>ทำไม?</b> ${x.why}</p><p><b>ความรู้ที่ควรเข้าใจ</b><br>${x.teach}</p><p><b>เทคนิคทำข้อสอบ</b><br>${x.tip}</p><button class="primary next" onclick="${i+1<run.length?"nextQ()":"finish()"}">${i+1<run.length?"ไปข้อถัดไป →":"จบภารกิจ →"}</button></div>`}
function nextQ(){i++;question();scrollTo(0,0)}
function finish(){shell(`<section class="hero"><div class="mascot">🏆</div><span class="pill">MISSION COMPLETE</span><h1>ภารกิจสำเร็จ!</h1><p>ทำไปแล้ว ${S.done} ข้อ · ถูก ${S.correct} ข้อ · XP ${S.xp}</p><button class="primary" onclick="start()">เล่นอีกครั้ง</button></section>`)}
function map(){let cats=[...new Set(BANK.map(x=>x.cat))];shell(`<div class="card"><h2>🗺️ แผนที่ด่าน</h2>${cats.map((c,n)=>`<div class="map"><div class="badge">${["🗣️","💻","🌏","🧠","📏","🏫"][n%6]}</div><div><b>${c}</b><div class="mini">ระบบเก็บสถิติหมวดนี้ให้คุณ</div></div></div>`).join("")}</div>`)}
function academy(){shell(`<div class="card"><span class="pill">ACADEMY</span><h2>🧠 หลักคิดที่ต้องใช้</h2><p><b>Alignment</b><br>เป้าหมาย กิจกรรม และการประเมินต้องสอดคล้องกัน</p><p><b>Validity</b><br>เริ่มจากสิ่งที่ต้องการวัด แล้วเลือกเครื่องมือให้ตรง</p><p><b>Digital Literacy</b><br>ความนิยมของข้อมูลไม่ใช่หลักฐานความจริง</p><p><b>Quality Cycle</b><br>ข้อมูล → วิเคราะห์ → ปรับปรุง → ติดตาม</p><p><b>Scaffolding</b><br>ช่วยเป็นขั้น ๆ แล้วค่อยลดการช่วย</p><button class="primary next" onclick="start()">นำความรู้ไปใช้ 🎯</button></div>`)}
function stats(){let rows=Object.entries(S.cat).map(([c,v])=>`<div class="stat"><span>${c}</span><b>${v.c}/${v.d}</b></div>`).join("");shell(`<div class="card"><h2>📊 ห้องวิเคราะห์</h2><div class="stat"><span>ทำสะสม</span><b>${S.done}</b></div><div class="stat"><span>ตอบถูก</span><b>${S.correct}</b></div><div class="stat"><span>ตอบผิด</span><b>${S.wrong}</b></div><h3>รายหมวด</h3>${rows||"<p class='mini'>เริ่มภารกิจเพื่อสร้างสถิติ</p>"}</div>`)}
home();