(()=>{
let S=ST.load(),Q=[],I=0,MODE='mission',cur;
const A=document.querySelector('#app'),$=s=>document.querySelector(s);
function hud(){['xp','streak','answered'].forEach(k=>{let e=$('#'+k);if(e)e.textContent=S[k]})}
function home(){A.innerHTML=`<section class="hero"><small>TEACHER QUEST • V6.1 STABLE</small><h1>ภารกิจพิชิตใบประกอบวิชาชีพครู ✨</h1><p>ข้อสอบแนวจากคลัง + โจทย์ต่อยอด • ตอบทีละข้อ • เฉลยแบบสอนให้เข้าใจ</p><div class="actions"><button class="primary" data-m="mission">🚀 เริ่มภารกิจ</button><button data-m="quick">⚡ Quick Run</button><button data-m="boss">👑 Boss Scenario</button><button data-m="study">📚 Study Run</button></div></section><section class="cards"><div>🧠 <b>เรียนจริง</b><p>เหตุผล จุดหลอก และเทคนิคจับโจทย์</p></div><div>🎯 <b>หลายหมวด</b><p>ไทย อังกฤษ ดิจิทัล โลก พอเพียง จิตวิทยา QA วัดผล หลักสูตร</p></div><div>📈 <b>เห็นพัฒนาการ</b><p>XP, streak และสถิติรายหมวด</p></div></section><div class="note">คลังตอนนี้ ${QS.length} ข้อ • จากแนวคลัง ${QS.filter(x=>x.source==='แนวจากคลัง').length} • ต่อยอด ${QS.filter(x=>x.source!=='แนวจากคลัง').length}</div>`;hud()}
function start(m){MODE=m;I=0;Q=EN.pick(m==='quick'?5:m==='boss'?8:10,m,S);render()}
function render(){cur=EN.build(Q[I]);A.innerHTML=`<div class="bar"><button id="back">← ออก</button><b>${I+1} / ${Q.length}</b></div><section class="card"><div class="tags"><span>${cur.category}</span><span>${'★'.repeat(cur.difficulty)}</span><span>${cur.source}</span></div><h2>${cur.q}</h2><div class="choices">${cur.o.map((o,i)=>`<button class="choice" data-i="${i}"><i>${i+1}</i><b>${o.text}</b></button>`).join('')}</div></section>`;$('#back').onclick=home;document.querySelectorAll('.choice').forEach(x=>x.onclick=()=>answer(+x.dataset.i))}
function answer(i){let o=cur.o[i],ok=o.ok;S.answered++;S.correct+=ok?1:0;S.xp+=EN.xp(cur,ok);S.streak=ok?S.streak+1:0;S.best=Math.max(S.best,S.streak);S.cat[cur.category]??={a:0,c:0};S.cat[cur.category].a++;if(ok)S.cat[cur.category].c++;S.seen.push(cur.id);ST.save(S);A.innerHTML=`<section class="result"><div class="big">${ok?'✓':'!'}</div><h2>${ok?'ถูกต้อง!':'ยังไม่ใช่'}</h2><div class="answer"><b>คำตอบที่ถูก</b><p>${cur.o.find(x=>x.ok).text}</p></div><article><h3>🧠 ทำไม?</h3><p>${cur.e}</p><div class="tip">🎯 <b>เทคนิค:</b> ${cur.t}</div></article><button class="primary next">${I+1<Q.length?'ข้อต่อไป →':'ดูผลภารกิจ →'}</button></section>`;$('.next').onclick=()=>{if(I+1<Q.length){I++;render()}else{summary()}}}
function summary(){A.innerHTML=`<section class="result"><small>MISSION COMPLETE</small><h1>ภารกิจสำเร็จ 🎉</h1><div class="score">${S.answered?Math.round(S.correct/S.answered*100):0}%</div><p>ถูก ${S.correct} จาก ${S.answered} ข้อ • ${S.xp} XP</p><button class="primary" id="again">เล่นอีกครั้ง</button> <button id="home">หน้าหลัก</button></section>`;$('#again').onclick=()=>start(MODE);$('#home').onclick=home}
document.addEventListener('click',e=>{let b=e.target.closest('[data-m]');if(b)start(b.dataset.m)});document.addEventListener('click',e=>{if(e.target.id==='reset'&&confirm('รีเซ็ตสถิติทั้งหมด?')){S=ST.reset();home()}});home();
})();